use_frameworks!

install! 'cocoapods', :share_schemes_for_development_pods => ['Staged']

target 'Staged_Example' do
  pod 'Staged', :path => '../'

  target 'Staged_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
