osx_image: xcode7.3
language: objective-c
before_install: rvm use $RVM_RUBY_VERSION
install: bundle install --without=documentation --path ../travis_bundle_dir
script:
  - set -o pipefail && xcodebuild test -workspace Example/Staged.xcworkspace -scheme Staged-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f coverage/cobertura.xml